#ifndef COSTANTI_H
#define COSTANTI_H

#define SIZE_ACCOUNT 20
#define SIZE_PASSWORD 20
#define ACCOUNTS_FILE "accounts_file.txt"
#define OPERATIONS_FILE "operations_file.txt"
#define MAX_CLIENTS 3
#define RIGHE_MAPPA 10
#define COLONNE_MAPPA 20
#define SKIN_GIOCATORE 'x'
#define NUMERO_OGGETTI 10
#define SKIN_OGGETTO 'o'
#define SKIN_GIOCATORE_SU_OGGETTO 'p'
#define SKIN_GIOCATORE_CON_OGGETTO 'L'
#define SKIN_GIOCATORE_CON_OGGETTO_SU_OGGETTO 'l'
#define SIZE_COLORE 7
#define SKIN_LOCAZIONE 'H'
#define NUMERO_LOCAZIONI 3
#define SKIN_GIOCATORE_SU_LOCAZIONE 'a'
#define SKIN_GIOCATORE_CON_OGGETTO_SU_LOCAZIONE 'A'
#define NUMERO_OSTACOLI 16
#define SKIN_OSTACOLO '@'
#define TEMPO_SESSIONE_PARTITA 45

#endif
